/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useThree} from "@react-three/fiber";

export default function Model({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/8B2.glb')

    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[0.03, 0, 3.19]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.97, 0.42, -0.97]}>
                <mesh geometry={nodes.Cylindre003.geometry} material={materials['Material.002']} />
                <mesh geometry={nodes.Cylindre003_1.geometry} material={materials['Material.003']} />
                <mesh geometry={nodes.Cylindre003_2.geometry} material={materials['Material.001']} />
            </group>
            <mesh geometry={nodes.ballDown.geometry} material={materials['default']} />
            <mesh
                geometry={nodes.BallTop.geometry}
                material={materials['default.001']}
                position={[0, 4.08, 0]}
                rotation={[Math.PI, 0, 0]}
            />
            <group position={[2.3, 0, 2.24]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={[-0.97, 0.42, -0.97]}>
                <mesh geometry={nodes.Cylindre004.geometry} material={materials['Material.005']} />
                <mesh geometry={nodes.Cylindre004_1.geometry} material={materials['Material.004']} />
                <mesh geometry={nodes.Cylindre004_2.geometry} material={materials['Material.006']} />
            </group>
            <group position={[2.38, 0, -2.37]} rotation={[-Math.PI / 2, 0, 2.36]} scale={[0.92, -0.4, 0.92]}>
                <mesh geometry={nodes.Cylindre013.geometry} material={materials['Material.015']} />
                <mesh geometry={nodes.Cylindre013_1.geometry} material={materials['Material.014']} />
                <mesh geometry={nodes.Cylindre013_2.geometry} material={materials['Material.013']} />
            </group>
            <group position={[-3.2, 0, -0.03]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[-0.97, 0.42, -0.97]}>
                <mesh geometry={nodes.Cylindre017.geometry} material={materials['Material.020']} />
                <mesh geometry={nodes.Cylindre017_1.geometry} material={materials['Material.021']} />
                <mesh geometry={nodes.Cylindre017_2.geometry} material={materials['Material.019']} />
            </group>
            <group position={[3.28, 0, -0.07]} rotation={[-Math.PI / 2, 0, 1.57]} scale={[-0.97, 0.42, -0.97]}>
                <mesh geometry={nodes.Cylindre009.geometry} material={materials['Material.008']} />
                <mesh geometry={nodes.Cylindre009_1.geometry} material={materials['Material.007']} />
                <mesh geometry={nodes.Cylindre009_2.geometry} material={materials['Material.009']} />
            </group>
            <group position={[-2.29, 0, 2.28]} rotation={[-Math.PI / 2, 0, -0.78]} scale={[0.92, -0.4, 0.92]}>
                <mesh geometry={nodes.Cylindre016.geometry} material={materials['Material.016']} />
                <mesh geometry={nodes.Cylindre016_1.geometry} material={materials['Material.017']} />
                <mesh geometry={nodes.Cylindre016_2.geometry} material={materials['Material.018']} />
            </group>
            <group position={[-2.22, 0, -2.39]} rotation={[-Math.PI / 2, 0, -2.36]} scale={[0.92, -0.4, 0.92]}>
                <mesh geometry={nodes.Cylindre022.geometry} material={materials['Material.022']} />
                <mesh geometry={nodes.Cylindre022_1.geometry} material={materials['Material.024']} />
                <mesh geometry={nodes.Cylindre022_2.geometry} material={materials['Material.023']} />
            </group>
            <group position={[0.05, 0, -3.29]} rotation={[-Math.PI / 2, 0, -3.14]} scale={[-0.97, 0.42, -0.97]}>
                <mesh geometry={nodes.Cylindre021.geometry} material={materials['Material.026']} />
                <mesh geometry={nodes.Cylindre021_1.geometry} material={materials['Material.025']} />
                <mesh geometry={nodes.Cylindre021_2.geometry} material={materials['Material.027']} />
            </group>

        </group>
    )
}

useGLTF.preload('/8B2.glb')
